name: Selenium Grid Standalone
version: "147.0.7727.55"
slug: selenium
description: Selenium Grid Standalone with Chrome add-on
url: https://github.com/SeleniumHQ/docker-selenium
webui: "http://[HOST]:[PORT:4444]"
watchdog: "http://[HOST]:[PORT:4444]/status"
arch:
  - amd64
init: false
ports:
  4444/tcp: 4444
  7900/tcp: 7900
environment:
  SE_NODE_MAX_SESSIONS: "4"
  SE_NODE_OVERRIDE_MAX_SESSIONS: "true"
image: "selenium/standalone-chrome"