name: Evolution API
version: "v2.3.0"
slug: evolutionapi
description: "API para controle do WhatsApp via HTTP"
url: "https://github.com/EvolutionAPI/evolution-api"
webui: "http://[HOST]:[PORT:49152]/manager/"
watchdog: "http://[HOST]:[PORT:49152]/"
init: false
startup: application
restart: "on-failure"
map:
  - data:rw
  - config:rw
arch:
  - amd64
options:
  SERVER_TYPE: http
  SERVER_HOST: "homeassistant"
  SERVER_PORT: 49152
  TZ: "America/Sao_Paulo"
  DATABASE_PROVIDER: postgresql
  DATABASE_USER: "user"
  DATABASE_PASSWORD: "pass"
  DATABASE_CONNECTION_URI: 'postgresql://user:pass@localhost:5432/evolution?schema=public'
  AUTHENTICATION_API_KEY: minha-senha-secreta
  PERSISTENCE_DIR: "/data"
  CUSTOM_ENV: >-
    DATABASE_SAVE_IS_ON_WHATSAPP_DAYS=1 DATABASE_SAVE_DATA_HISTORIC=false DATABASE_SAVE_DATA_NEW_MESSAGE=false
schema:
  SERVER_TYPE: "str?"
  SERVER_HOST: "str?"
  SERVER_PORT: "int?"
  TZ: "str?"
  DATABASE_PROVIDER: "str?"
  DATABASE_USER: "str?"
  DATABASE_PASSWORD: "str?"
  DATABASE_CONNECTION_URI: "str?"
  AUTHENTICATION_API_KEY: "str?"
  PERSISTENCE_DIR: >-
    match(^(/(data|config/addons_config/evolution-api))$)
  CUSTOM_ENV: >-
    match(^(([A-Z0-9_]+=(\"[^\"]*\"|'[^']*'|[^ ]+))( +[A-Z0-9_]+=(\"[^\"]*\"|'[^']*'|[^ ]+))*)?$)
ports:
  49152/tcp: 49152
image: "ghcr.io/tiagok-777/evolution-api-addon"