name: Build & Publish Evolution API Docker Image
on:
  push:
    branches:
      - main
    paths:
      - 'evolution-api-addon/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-docker-addon:
    name: Build Docker Image - Evolution API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Extract version from config.yaml
        id: extract_version
        run: |
          if [ ! -f "evolution-api-addon/config.yaml" ]; then
            echo "Error: config.yaml not found"
            exit 1
          fi
          VERSION=$(grep 'version:' evolution-api-addon/config.yaml | cut -d'"' -f2)
          echo "version_from_config=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/evolution-api-addon
          tags: |
            type=raw, value=${{ steps.extract_version.outputs.version_from_config }}
            type=raw, value=latest
            type=sha, format=short
            
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./evolution-api-addon
          file: ./evolution-api-addon/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max