name: Update CHANGELOG on version bump
on:
  pull_request_target:
    paths:
      - '**/config.yaml' # Este trigger está OK, pois ele captura qualquer mudança que queremos no futuro
    types:
      - opened
      - synchronize
permissions:
  contents: write
jobs:
  update-changelog:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon:
          - name: wpp-connect-addon
            config_path: wpp-connect-addon/config.yaml
            changelog_path: wpp-connect-addon/CHANGELOG.md
            release_repo: wppconnect-team/wppconnect-server
          - name: frigate-notify-addon
            config_path: frigate-notify-addon/config.yaml
            changelog_path: frigate-notify-addon/CHANGELOG.md
            release_repo: 0x2142/frigate-notify
    if: github.actor == 'renovate[bot]'
    steps:
      - name: Check out the PR branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}

      # **IMPORTANTE:** ADICIONE ESTE PASSO PARA OBTER A LISTA DE ARQUIVOS ALTERADOS
      # Isso é necessário porque `pull_request_target` tem escopo limitado por segurança
      # para `github.event.pull_request.changed_files` antes do checkout completo.
      - name: Get changed files (for `pull_request_target` context)
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files_yaml: |
            ${{ matrix.addon.config_path }}

      - name: Debug - List files in addon directory
        run: ls -la ${{ matrix.addon.name }} # Este passo pode rodar para todos os addons da matriz

      - name: Extract new version from config.yaml for ${{ matrix.addon.name }}
        id: extract
        # **NOVA CONDIÇÃO AQUI:** Só roda se o config.yaml deste addon foi alterado.
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          if [ ! -f "${{ matrix.addon.config_path }}" ]; then
            echo "Error: config.yaml not found at ${{ matrix.addon.config_path }}"
            exit 1
          fi
          NEW_VERSION=$(grep 'version:' "${{ matrix.addon.config_path }}" | sed -E 's/version:\s*"([^"]+)".*/\1/')
          
          echo "Debug: Extracted version -> $NEW_VERSION"
          if [ -z "$NEW_VERSION" ]; then
            echo "Warning: No version extracted from ${{ matrix.addon.config_path }}. This might be normal if the config wasn't updated."
            echo "version=" >> $GITHUB_OUTPUT
          else
            echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          fi

      - name: Get release info from GitHub for ${{ matrix.addon.name }}
        id: release
        # **NOVA CONDIÇÃO AQUI:** Só roda se o config.yaml deste addon foi alterado E se uma versão foi extraída.
        if: steps.changed-files.outputs.any_changed == 'true' && steps.extract.outputs.version != ''
        run: |
          VERSION="${{ steps.extract.outputs.version }}"
          # A lógica `if [ -z "$VERSION" ]` pode ser removida se o `if` do step garantir a versão.
          # Mas mantê-la como uma checagem de segurança não faz mal.
          # Resto do script do 'Get release info'

      - name: Prepend to CHANGELOG.md for ${{ matrix.addon.name }}
        # **NOVA CONDIÇÃO AQUI:** Só roda se o config.yaml deste addon foi alterado E se uma versão foi extraída.
        if: steps.changed-files.outputs.any_changed == 'true' && steps.extract.outputs.version != ''
        run: |
          VERSION="${{ steps.extract.outputs.version }}"
          # Resto do script do 'Prepend'

      - name: Commit and push changes for ${{ matrix.addon.name }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file_pattern: ${{ matrix.addon.changelog_path }}
          branch: ${{ github.event.pull_request.head.ref }}
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_message: |
            docs(${
              {
                'wpp-connect-addon': 'wpp-connect',
                'frigate-notify-addon': 'frigate-notify'
              }[matrix.addon.name] or 'general'
            }): update CHANGELOG for ${{ matrix.addon.name }} version ${{ steps.extract.outputs.version }}
          push_options: --force
        # **NOVA CONDIÇÃO AQUI:** Só roda se o config.yaml deste addon foi alterado E se uma versão foi extraída.
        if: steps.changed-files.outputs.any_changed == 'true' && steps.extract.outputs.version != ''